# Generated by Django 6.0.4 on 2026-05-02 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('stores', 'Stores'), ('users', 'Users'), ('mappings', 'Mappings')], max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.CharField(max_length=64, unique=True)),
                ('store_external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.state')),
                ('store_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.storebrand')),
                ('store_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='files.storetype')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='files.user')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentJourneyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='files.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='files.user')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('column', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='files.ingestionjob')),
            ],
            options={
                'ordering': ('row_number', 'id'),
                'indexes': [models.Index(fields=['job', 'row_number'], name='files_inges_job_id_9a41f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_id'], name='files_store_store_i_c0f130_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_external_id'], name='files_store_store_e_520b58_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='files_user_usernam_499799_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='files_user_email_fa4c95_idx'),
        ),
        migrations.AddIndex(
            model_name='permanentjourneyplan',
            index=models.Index(fields=['date'], name='files_perma_date_c53d34_idx'),
        ),
        migrations.AddIndex(
            model_name='permanentjourneyplan',
            index=models.Index(fields=['user', 'date'], name='files_perma_user_id_c14bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='permanentjourneyplan',
            index=models.Index(fields=['store', 'date'], name='files_perma_store_i_3e6163_idx'),
        ),
        migrations.AddConstraint(
            model_name='permanentjourneyplan',
            constraint=models.UniqueConstraint(fields=('user', 'store', 'date'), name='unique_user_store_date_journey_plan'),
        ),
    ]
